// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;

/**
 * Cartecredit generated by hbm2java
 */
public class Cartecredit implements java.io.Serializable {

	private String numero;
	private Client client;
	private String type;
	private BigInteger expirationmois;
	private BigInteger expirationannee;
	private BigInteger cvv;

	public Cartecredit() {
	}

	public Cartecredit(String numero, Client client, String type, BigInteger expirationmois,
			BigInteger expirationannee) {
		this.numero = numero;
		this.client = client;
		this.type = type;
		this.expirationmois = expirationmois;
		this.expirationannee = expirationannee;
	}

	public Cartecredit(String numero, Client client, String type, BigInteger expirationmois, BigInteger expirationannee,
			BigInteger cvv) {
		this.numero = numero;
		this.client = client;
		this.type = type;
		this.expirationmois = expirationmois;
		this.expirationannee = expirationannee;
		this.cvv = cvv;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public BigInteger getExpirationmois() {
		return this.expirationmois;
	}

	public void setExpirationmois(BigInteger expirationmois) {
		this.expirationmois = expirationmois;
	}

	public BigInteger getExpirationannee() {
		return this.expirationannee;
	}

	public void setExpirationannee(BigInteger expirationannee) {
		this.expirationannee = expirationannee;
	}

	public BigInteger getCvv() {
		return this.cvv;
	}

	public void setCvv(BigInteger cvv) {
		this.cvv = cvv;
	}

}
