// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

/**
 * Clienttest generated by hbm2java
 */
public class Clienttest implements java.io.Serializable {

	private ClienttestId id;

	public Clienttest() {
	}

	public Clienttest(ClienttestId id) {
		this.id = id;
	}

	public ClienttestId getId() {
		return this.id;
	}

	public void setId(ClienttestId id) {
		this.id = id;
	}

}
