// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

/**
 * ClienttestId generated by hbm2java
 */
public class ClienttestId implements java.io.Serializable {

	private long idclient;
	private String prenom;

	public ClienttestId() {
	}

	public ClienttestId(long idclient, String prenom) {
		this.idclient = idclient;
		this.prenom = prenom;
	}

	public long getIdclient() {
		return this.idclient;
	}

	public void setIdclient(long idclient) {
		this.idclient = idclient;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienttestId))
			return false;
		ClienttestId castOther = (ClienttestId) other;

		return (this.getIdclient() == castOther.getIdclient())
				&& ((this.getPrenom() == castOther.getPrenom()) || (this.getPrenom() != null
						&& castOther.getPrenom() != null && this.getPrenom().equals(castOther.getPrenom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdclient();
		result = 37 * result + (getPrenom() == null ? 0 : this.getPrenom().hashCode());
		return result;
	}

}
