// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Copiefilm generated by hbm2java
 */
public class Copiefilm implements java.io.Serializable {

	private BigInteger code;
	private Film film;
	private boolean eninventaire;
	private Set locationfilms = new HashSet(0);

	public Copiefilm() {
	}

	public Copiefilm(BigInteger code, Film film, boolean eninventaire) {
		this.code = code;
		this.film = film;
		this.eninventaire = eninventaire;
	}

	public Copiefilm(BigInteger code, Film film, boolean eninventaire, Set locationfilms) {
		this.code = code;
		this.film = film;
		this.eninventaire = eninventaire;
		this.locationfilms = locationfilms;
	}

	public BigInteger getCode() {
		return this.code;
	}

	public void setCode(BigInteger code) {
		this.code = code;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public boolean isEninventaire() {
		return this.eninventaire;
	}

	public void setEninventaire(boolean eninventaire) {
		this.eninventaire = eninventaire;
	}

	public Set getLocationfilms() {
		return this.locationfilms;
	}

	public void setLocationfilms(Set locationfilms) {
		this.locationfilms = locationfilms;
	}

}
