// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film implements java.io.Serializable {

	private BigInteger idfilm;
	private Realisateur realisateur;
	private String titre;
	private BigInteger anneesortie;
	private String langueoriginale;
	private BigInteger duree;
	private BigInteger nbcopiesdispo;
	private String resumescenario;
	private String affiche;
	private Set genres = new HashSet(0);
	private Set personnages = new HashSet(0);
	private Set copiefilms = new HashSet(0);
	private Set scenaristes = new HashSet(0);
	private Set paysproductions = new HashSet(0);
	private Set bandeannonces = new HashSet(0);

	public Film() {
	}

	public Film(BigInteger idfilm, Realisateur realisateur, String titre, BigInteger nbcopiesdispo) {
		this.idfilm = idfilm;
		this.realisateur = realisateur;
		this.titre = titre;
		this.nbcopiesdispo = nbcopiesdispo;
	}

	public Film(BigInteger idfilm, Realisateur realisateur, String titre, BigInteger anneesortie,
			String langueoriginale, BigInteger duree, BigInteger nbcopiesdispo, String resumescenario, String affiche,
			Set genres, Set personnages, Set copiefilms, Set scenaristes, Set paysproductions, Set bandeannonces) {
		this.idfilm = idfilm;
		this.realisateur = realisateur;
		this.titre = titre;
		this.anneesortie = anneesortie;
		this.langueoriginale = langueoriginale;
		this.duree = duree;
		this.nbcopiesdispo = nbcopiesdispo;
		this.resumescenario = resumescenario;
		this.affiche = affiche;
		this.genres = genres;
		this.personnages = personnages;
		this.copiefilms = copiefilms;
		this.scenaristes = scenaristes;
		this.paysproductions = paysproductions;
		this.bandeannonces = bandeannonces;
	}

	public BigInteger getIdfilm() {
		return this.idfilm;
	}

	public void setIdfilm(BigInteger idfilm) {
		this.idfilm = idfilm;
	}

	public Realisateur getRealisateur() {
		return this.realisateur;
	}

	public void setRealisateur(Realisateur realisateur) {
		this.realisateur = realisateur;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public BigInteger getAnneesortie() {
		return this.anneesortie;
	}

	public void setAnneesortie(BigInteger anneesortie) {
		this.anneesortie = anneesortie;
	}

	public String getLangueoriginale() {
		return this.langueoriginale;
	}

	public void setLangueoriginale(String langueoriginale) {
		this.langueoriginale = langueoriginale;
	}

	public BigInteger getDuree() {
		return this.duree;
	}

	public void setDuree(BigInteger duree) {
		this.duree = duree;
	}

	public BigInteger getNbcopiesdispo() {
		return this.nbcopiesdispo;
	}

	public void setNbcopiesdispo(BigInteger nbcopiesdispo) {
		this.nbcopiesdispo = nbcopiesdispo;
	}

	public String getResumescenario() {
		return this.resumescenario;
	}

	public void setResumescenario(String resumescenario) {
		this.resumescenario = resumescenario;
	}

	public String getAffiche() {
		return this.affiche;
	}

	public void setAffiche(String affiche) {
		this.affiche = affiche;
	}

	public Set getGenres() {
		return this.genres;
	}

	public void setGenres(Set genres) {
		this.genres = genres;
	}

	public Set getPersonnages() {
		return this.personnages;
	}

	public void setPersonnages(Set personnages) {
		this.personnages = personnages;
	}

	public Set getCopiefilms() {
		return this.copiefilms;
	}

	public void setCopiefilms(Set copiefilms) {
		this.copiefilms = copiefilms;
	}

	public Set getScenaristes() {
		return this.scenaristes;
	}

	public void setScenaristes(Set scenaristes) {
		this.scenaristes = scenaristes;
	}

	public Set getPaysproductions() {
		return this.paysproductions;
	}

	public void setPaysproductions(Set paysproductions) {
		this.paysproductions = paysproductions;
	}

	public Set getBandeannonces() {
		return this.bandeannonces;
	}

	public void setBandeannonces(Set bandeannonces) {
		this.bandeannonces = bandeannonces;
	}

}
