// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait implements java.io.Serializable {

	private char codeforfait;
	private String nom;
	private BigInteger cout;
	private BigInteger locationmax;
	private BigInteger dureemax;
	private Set clients = new HashSet(0);

	public Forfait() {
	}

	public Forfait(char codeforfait) {
		this.codeforfait = codeforfait;
	}

	public Forfait(char codeforfait, String nom, BigInteger cout, BigInteger locationmax, BigInteger dureemax,
			Set clients) {
		this.codeforfait = codeforfait;
		this.nom = nom;
		this.cout = cout;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
		this.clients = clients;
	}

	public char getCodeforfait() {
		return this.codeforfait;
	}

	public void setCodeforfait(char codeforfait) {
		this.codeforfait = codeforfait;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigInteger getCout() {
		return this.cout;
	}

	public void setCout(BigInteger cout) {
		this.cout = cout;
	}

	public BigInteger getLocationmax() {
		return this.locationmax;
	}

	public void setLocationmax(BigInteger locationmax) {
		this.locationmax = locationmax;
	}

	public BigInteger getDureemax() {
		return this.dureemax;
	}

	public void setDureemax(BigInteger dureemax) {
		this.dureemax = dureemax;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
