// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable {

	private BigInteger idgenre;
	private String genre;
	private Set films = new HashSet(0);

	public Genre() {
	}

	public Genre(BigInteger idgenre) {
		this.idgenre = idgenre;
	}

	public Genre(BigInteger idgenre, String genre, Set films) {
		this.idgenre = idgenre;
		this.genre = genre;
		this.films = films;
	}

	public BigInteger getIdgenre() {
		return this.idgenre;
	}

	public void setIdgenre(BigInteger idgenre) {
		this.idgenre = idgenre;
	}

	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public Set getFilms() {
		return this.films;
	}

	public void setFilms(Set films) {
		this.films = films;
	}

}
