// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Paysproduction generated by hbm2java
 */
public class Paysproduction implements java.io.Serializable {

	private BigInteger idpaysproduction;
	private String pays;
	private Set films = new HashSet(0);

	public Paysproduction() {
	}

	public Paysproduction(BigInteger idpaysproduction, String pays) {
		this.idpaysproduction = idpaysproduction;
		this.pays = pays;
	}

	public Paysproduction(BigInteger idpaysproduction, String pays, Set films) {
		this.idpaysproduction = idpaysproduction;
		this.pays = pays;
		this.films = films;
	}

	public BigInteger getIdpaysproduction() {
		return this.idpaysproduction;
	}

	public void setIdpaysproduction(BigInteger idpaysproduction) {
		this.idpaysproduction = idpaysproduction;
	}

	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public Set getFilms() {
		return this.films;
	}

	public void setFilms(Set films) {
		this.films = films;
	}

}
