// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;

/**
 * Personnage generated by hbm2java
 */
public class Personnage implements java.io.Serializable {

	private BigInteger idpersonnage;
	private Film film;
	private Personne personne;
	private String personnage;

	public Personnage() {
	}

	public Personnage(BigInteger idpersonnage, Film film, Personne personne) {
		this.idpersonnage = idpersonnage;
		this.film = film;
		this.personne = personne;
	}

	public Personnage(BigInteger idpersonnage, Film film, Personne personne, String personnage) {
		this.idpersonnage = idpersonnage;
		this.film = film;
		this.personne = personne;
		this.personnage = personnage;
	}

	public BigInteger getIdpersonnage() {
		return this.idpersonnage;
	}

	public void setIdpersonnage(BigInteger idpersonnage) {
		this.idpersonnage = idpersonnage;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getPersonnage() {
		return this.personnage;
	}

	public void setPersonnage(String personnage) {
		this.personnage = personnage;
	}

}
