// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	private BigInteger idpersonne;
	private String nom;
	private Date datenaissance;
	private String lieunaissance;
	private String photo;
	private String biographie;
	private Set realisateurs = new HashSet(0);
	private Set personnages = new HashSet(0);

	public Personne() {
	}

	public Personne(BigInteger idpersonne) {
		this.idpersonne = idpersonne;
	}

	public Personne(BigInteger idpersonne, String nom, Date datenaissance, String lieunaissance, String photo,
			String biographie, Set realisateurs, Set personnages) {
		this.idpersonne = idpersonne;
		this.nom = nom;
		this.datenaissance = datenaissance;
		this.lieunaissance = lieunaissance;
		this.photo = photo;
		this.biographie = biographie;
		this.realisateurs = realisateurs;
		this.personnages = personnages;
	}

	public BigInteger getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(BigInteger idpersonne) {
		this.idpersonne = idpersonne;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	public String getLieunaissance() {
		return this.lieunaissance;
	}

	public void setLieunaissance(String lieunaissance) {
		this.lieunaissance = lieunaissance;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getBiographie() {
		return this.biographie;
	}

	public void setBiographie(String biographie) {
		this.biographie = biographie;
	}

	public Set getRealisateurs() {
		return this.realisateurs;
	}

	public void setRealisateurs(Set realisateurs) {
		this.realisateurs = realisateurs;
	}

	public Set getPersonnages() {
		return this.personnages;
	}

	public void setPersonnages(Set personnages) {
		this.personnages = personnages;
	}

}
