// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Realisateur generated by hbm2java
 */
public class Realisateur implements java.io.Serializable {

	private BigInteger idrealisateur;
	private Personne personne;
	private Set films = new HashSet(0);

	public Realisateur() {
	}

	public Realisateur(BigInteger idrealisateur, Personne personne) {
		this.idrealisateur = idrealisateur;
		this.personne = personne;
	}

	public Realisateur(BigInteger idrealisateur, Personne personne, Set films) {
		this.idrealisateur = idrealisateur;
		this.personne = personne;
		this.films = films;
	}

	public BigInteger getIdrealisateur() {
		return this.idrealisateur;
	}

	public void setIdrealisateur(BigInteger idrealisateur) {
		this.idrealisateur = idrealisateur;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Set getFilms() {
		return this.films;
	}

	public void setFilms(Set films) {
		this.films = films;
	}

}
