// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;

/**
 * Scenariste generated by hbm2java
 */
public class Scenariste implements java.io.Serializable {

	private BigInteger idscenariste;
	private Film film;
	private String nom;

	public Scenariste() {
	}

	public Scenariste(BigInteger idscenariste, Film film) {
		this.idscenariste = idscenariste;
		this.film = film;
	}

	public Scenariste(BigInteger idscenariste, Film film, String nom) {
		this.idscenariste = idscenariste;
		this.film = film;
		this.nom = nom;
	}

	public BigInteger getIdscenariste() {
		return this.idscenariste;
	}

	public void setIdscenariste(BigInteger idscenariste) {
		this.idscenariste = idscenariste;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
