// default package
// Generated Feb 15, 2020 2:25:06 PM by Hibernate Tools 5.4.7.Final

/**
 * Vinfofilm generated by hbm2java
 */
public class Vinfofilm implements java.io.Serializable {

	private VinfofilmId id;

	public Vinfofilm() {
	}

	public Vinfofilm(VinfofilmId id) {
		this.id = id;
	}

	public VinfofilmId getId() {
		return this.id;
	}

	public void setId(VinfofilmId id) {
		this.id = id;
	}

}
